int soNgayMuon(char ngaymuon[]);
void thongKeSach();
void thongKeSachTheoLoai();
void thongKeDocGia();
void thongKeDocGiaTheoGioiTinh();
void thongKeSachDangMuon();
void thongKeDocGiaTreHan();
void statisticMenu(int rank, char **currenUser);
int countLine(char *filename);
void xoaPhanTu(char *a, int pos, int &n);